# Generated by Django 4.1.5 on 2023-12-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoTask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
