# Generated by Django 4.2.8 on 2023-12-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.TextField()),
            ],
        ),
    ]
