# Generated by Django 4.1.5 on 2023-12-05 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_id_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskId',
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
